spring.application.name=trade-engine
server.port=8080

# Expose the metrics endpoint for Prometheus to scrape
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.enabled=true

# Add detailed health info 
management.endpoint.health.show-details=always