apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trade-clearing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LongTran112/c7-clearing-project.git
    targetRevision: development
    path: environments/development/apps/trade-engine
    helm:
      releaseName: trade-engine
  destination:
    server: https://kubernetes.default.svc
    namespace: trade-engine
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
