apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-app-secret
  namespace: trade-engine
spec:
  secretStoreRef:
    name: gcp-sm
    kind: ClusterSecretStore
  target:
    name: my-app-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        key: db-url
        version: latest
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: db-username
        version: latest
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: db-password
        version: latest
