apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    chart: sonarqube
    targetRevision: 2025.5.0
    helm:
      releaseName: sonarqube
      values: |
        # NOTE: SonarQube is resource/storage heavy.
        # You will likely need a default StorageClass and enough CPU/RAM.
        edition: developer
        monitoringPasscode: "sonarqube-monitoring-passcode-2024"
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
