{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.ingress.rateLimit.enabled }}
    {{- if eq .Values.ingress.className "nginx" }}
    nginx.ingress.kubernetes.io/limit-rps: "{{ .Values.ingress.rateLimit.rps }}"
    nginx.ingress.kubernetes.io/limit-rpm: "{{ .Values.ingress.rateLimit.rpm }}"
    nginx.ingress.kubernetes.io/limit-connections: "{{ .Values.ingress.rateLimit.connections }}"
    {{- if .Values.ingress.rateLimit.burst }}
    nginx.ingress.kubernetes.io/limit-burst: "{{ .Values.ingress.rateLimit.burst }}"
    {{- end }}
    {{- if .Values.ingress.rateLimit.whitelist }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.ingress.rateLimit.whitelist }}"
    {{- end }}
    {{- end }}
    {{- if eq .Values.ingress.className "traefik" }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-rate-limit@kubernetescrd
    {{- end }}
    {{- end }}
    {{- if .Values.ingress.tls }}
    nginx.ingress.kubernetes.io/ssl-redirect: "{{ .Values.ingress.sslRedirect }}"
    {{- end }}
    {{- if .Values.ingress.nginxConfig }}
    {{- range $key, $value := .Values.ingress.nginxConfig }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        {{- if ne .host "*" }}
        - {{ .host }}
        {{- end }}
        {{- end }}
      {{- if .Values.ingress.tlsSecretName }}
      secretName: {{ .Values.ingress.tlsSecretName }}
      {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    {{- if ne .host "*" }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $.Values.service.name }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- else }}
    - http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $.Values.service.name }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
    {{- end }}
{{- end }}

