apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-engine
  namespace: default
spec:
  replicas: 1 # We start with 1 instance
  selector:
    matchLabels:
      app: trade-engine
  template:
    metadata:
      labels:
        app: trade-engine
    spec:
      containers:
      - name: trade-engine
        # THIS IS YOUR IMAGE FROM PHASE 3
        image: longtran112/trade-engine:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
