apiVersion: v1
kind: Service
metadata:
  name: trade-engine-service
  namespace: default
  labels:                  
    app: trade-engine      
spec:
  type: NodePort
  selector:
    app: trade-engine      
  ports:
    - name: http           
      port: 8080
      targetPort: 8080
      nodePort: 30080