apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.fairwinds.com/stable
    chart: vpa
    targetRevision: 1.7.0
    helm:
      releaseName: vpa
      values: |
        installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vpa-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
